version: '3'
services:
  frontend:
    build: .
    ports:
      - "3300:80"
    volumes:
      - .:/app
      - /app/node_modules
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=development
